version: 2

models:
  - name: downstream_orders
    description: "Downstream orders enriched with tier classification (dbt-loom approach)"
    columns:
      - name: order_id
        description: "Unique order identifier from upstream"
      - name: status
        description: "Order status from upstream"
      - name: amount
        description: "Order amount from upstream"
      - name: created_at
        description: "Creation timestamp from upstream"
      - name: order_tier
        description: "Derived order tier based on amount"
      - name: processed_by
        description: "Identifier for which downstream project processed this"
